-- Add new XpReason values for gamification v2 events
ALTER TYPE "XpReason" ADD VALUE IF NOT EXISTS 'FIRST_BOOKING';
ALTER TYPE "XpReason" ADD VALUE IF NOT EXISTS 'FIRST_CONSULTANCY';
ALTER TYPE "XpReason" ADD VALUE IF NOT EXISTS 'EVERY_10_BOOKINGS';
ALTER TYPE "XpReason" ADD VALUE IF NOT EXISTS 'STREAK_MILESTONE_15';
ALTER TYPE "XpReason" ADD VALUE IF NOT EXISTS 'STREAK_MILESTONE_30';
ALTER TYPE "XpReason" ADD VALUE IF NOT EXISTS 'STREAK_MILESTONE_45';
ALTER TYPE "XpReason" ADD VALUE IF NOT EXISTS 'STREAK_MILESTONE_90';
